---
env:
  es2021: true
  browser: true
  amd: true
  node: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  project: ./tsconfig.json
extends:
  - '@logux/eslint-config/ts'
plugins:
  - '@typescript-eslint'
  - security
  - unicorn
  - import
ignorePatterns:
  - '**/lib'
  - '**/coverage'
  - '**/*.test_disabled.*'
  - 'vitest.config.ts'
rules:
  no-shadow: 'off'
  '@typescript-eslint/no-shadow': ['error']
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'
      caughtErrorsIgnorePattern: '^_'
  import/extensions:
    - 'error'
    - always
    - js: always
  prefer-let/prefer-let: 'off'
  prefer-const: ['error']
