import type { NextPage } from 'next'
import Head from 'next/head'
import { useTodos } from '../stores/todosStore'

const Home: NextPage = () => {
  const todos = useTodos()
  const todosArray = Array.from(todos.values())
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container max-w-lg mx-auto px-4">
        <h1 className="text-2xl my-4">Todos: {todos.size}</h1>
        {todosArray.map(({ id, text }) => {
          return (
            <div key={id} className="flex items-center justify-between">
              <span>{text}</span>
              <button
                className="bg-red-500 text-white px-2 rounded"
                onClick={() => todos.delete(id)}
              >
                Delete
              </button>
            </div>
          )
        })}
      </main>
      <footer>footer</footer>
    </>
  )
}

export default Home
